"""initial reco schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 20:35:33.702695
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS reco")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('brand_id', name=op.f('pk_brands')),
    sa.UniqueConstraint('external_id', name=op.f('uq_brands_external_id')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name')),
    schema='reco'
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['reco.categories.category_id'], name=op.f('fk_categories_parent_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories')),
    sa.UniqueConstraint('external_id', name=op.f('uq_categories_external_id')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    schema='reco'
    )
    op.create_index(op.f('ix_categories_parent_category_id'), 'categories', ['parent_category_id'], unique=False, schema='reco')
    op.create_table('concerns',
    sa.Column('concern_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=96), nullable=False),
    sa.PrimaryKeyConstraint('concern_id', name=op.f('pk_concerns')),
    sa.UniqueConstraint('name', name=op.f('uq_concerns_name')),
    schema='reco'
    )
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('name', name=op.f('uq_ingredients_name')),
    schema='reco'
    )
    op.create_index(op.f('ix_ingredients_family'), 'ingredients', ['family'], unique=False, schema='reco')
    op.create_table('skin_types',
    sa.Column('skin_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('skin_type_id', name=op.f('pk_skin_types')),
    sa.UniqueConstraint('name', name=op.f('uq_skin_types_name')),
    schema='reco'
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('external_id', name=op.f('uq_users_external_id')),
    schema='reco'
    )
    op.create_table('beauty_profiles',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('skin_type_id', sa.Integer(), nullable=True),
    sa.Column('sensitivity', sa.SmallInteger(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='DZD', nullable=False),
    sa.Column('fragrance_preference', sa.String(length=24), server_default='no_preference', nullable=False),
    sa.Column('texture_preference', sa.String(length=24), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fragrance_preference IN ('no_preference', 'fragrance_free', 'likes_fragrance')", name=op.f('ck_beauty_profiles_fragrance_preference_values')),
    sa.CheckConstraint('budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max', name=op.f('ck_beauty_profiles_budget_range')),
    sa.CheckConstraint('budget_min IS NULL OR budget_min >= 0', name=op.f('ck_beauty_profiles_budget_min_positive')),
    sa.CheckConstraint('sensitivity IS NULL OR sensitivity BETWEEN 0 AND 5', name=op.f('ck_beauty_profiles_sensitivity_range')),
    sa.ForeignKeyConstraint(['skin_type_id'], ['reco.skin_types.skin_type_id'], name=op.f('fk_beauty_profiles_skin_type_id_skin_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['reco.users.user_id'], name=op.f('fk_beauty_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_beauty_profiles')),
    schema='reco'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='DZD', nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['reco.users.user_id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders')),
    sa.UniqueConstraint('external_id', name=op.f('uq_orders_external_id')),
    schema='reco'
    )
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False, schema='reco')
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='DZD', nullable=False),
    sa.Column('available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('routine_role', sa.String(length=16), server_default='OTHER', nullable=False),
    sa.Column('routine_role_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('texture', sa.String(length=24), nullable=True),
    sa.Column('usage_time', sa.String(length=3), nullable=True),
    sa.Column('is_bundle', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('core_sync', 'dev_seed', 'manual')", name=op.f('ck_products_data_source_values')),
    sa.CheckConstraint("routine_role IN ('CLEANSER', 'TONER', 'SERUM', 'TREATMENT', 'MOISTURIZER', 'SUNSCREEN', 'EYE_CARE', 'MASK', 'MAKEUP', 'OTHER')", name=op.f('ck_products_routine_role_values')),
    sa.CheckConstraint("usage_time IS NULL OR usage_time IN ('AM', 'PM', 'ANY')", name=op.f('ck_products_usage_time_values')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_products_price_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['reco.brands.brand_id'], name=op.f('fk_products_brand_id_brands'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['reco.categories.category_id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products')),
    sa.UniqueConstraint('external_id', name=op.f('uq_products_external_id')),
    schema='reco'
    )
    op.create_index('ix_products_available_role', 'products', ['available', 'routine_role'], unique=False, schema='reco')
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False, schema='reco')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False, schema='reco')
    op.create_table('user_brand_preferences',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['reco.brands.brand_id'], name=op.f('fk_user_brand_preferences_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['reco.users.user_id'], name=op.f('fk_user_brand_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'brand_id', name=op.f('pk_user_brand_preferences')),
    schema='reco'
    )
    op.create_table('user_category_preferences',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['reco.categories.category_id'], name=op.f('fk_user_category_preferences_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['reco.users.user_id'], name=op.f('fk_user_category_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_user_category_preferences')),
    schema='reco'
    )
    op.create_table('user_concerns',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('concern_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('priority BETWEEN 1 AND 10', name=op.f('ck_user_concerns_priority_range')),
    sa.ForeignKeyConstraint(['concern_id'], ['reco.concerns.concern_id'], name=op.f('fk_user_concerns_concern_id_concerns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['reco.users.user_id'], name=op.f('fk_user_concerns_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'concern_id', name=op.f('pk_user_concerns')),
    schema='reco'
    )
    op.create_table('user_ingredient_preferences',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("preference_type IN ('PREFER', 'AVOID')", name=op.f('ck_user_ingredient_preferences_preference_type_values')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['reco.ingredients.ingredient_id'], name=op.f('fk_user_ingredient_preferences_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['reco.users.user_id'], name=op.f('fk_user_ingredient_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'ingredient_id', name=op.f('pk_user_ingredient_preferences')),
    schema='reco'
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['reco.orders.order_id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['reco.products.product_id'], name=op.f('fk_order_items_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name=op.f('pk_order_items')),
    schema='reco'
    )
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False, schema='reco')
    op.create_table('product_concerns',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('concern_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.CheckConstraint('relevance_score BETWEEN 0 AND 1', name=op.f('ck_product_concerns_relevance_range')),
    sa.ForeignKeyConstraint(['concern_id'], ['reco.concerns.concern_id'], name=op.f('fk_product_concerns_concern_id_concerns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['reco.products.product_id'], name=op.f('fk_product_concerns_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'concern_id', name=op.f('pk_product_concerns')),
    schema='reco'
    )
    op.create_index(op.f('ix_product_concerns_concern_id'), 'product_concerns', ['concern_id'], unique=False, schema='reco')
    op.create_table('product_ingredients',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['reco.ingredients.ingredient_id'], name=op.f('fk_product_ingredients_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['reco.products.product_id'], name=op.f('fk_product_ingredients_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'ingredient_id', name=op.f('pk_product_ingredients')),
    schema='reco'
    )
    op.create_index(op.f('ix_product_ingredients_ingredient_id'), 'product_ingredients', ['ingredient_id'], unique=False, schema='reco')
    op.create_table('product_skin_types',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('skin_type_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.CheckConstraint('compatibility_score BETWEEN 0 AND 1', name=op.f('ck_product_skin_types_compatibility_range')),
    sa.ForeignKeyConstraint(['product_id'], ['reco.products.product_id'], name=op.f('fk_product_skin_types_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skin_type_id'], ['reco.skin_types.skin_type_id'], name=op.f('fk_product_skin_types_skin_type_id_skin_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'skin_type_id', name=op.f('pk_product_skin_types')),
    schema='reco'
    )
    op.create_index(op.f('ix_product_skin_types_skin_type_id'), 'product_skin_types', ['skin_type_id'], unique=False, schema='reco')
    op.create_table('product_stats',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('popularity_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('view_count_30d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wishlist_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cart_count_30d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('purchase_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['reco.products.product_id'], name=op.f('fk_product_stats_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product_stats')),
    schema='reco'
    )
    op.create_table('user_events',
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("event_type IN ('IMPRESSION', 'VIEW', 'CLICK', 'SEARCH', 'WISHLIST_ADD', 'WISHLIST_REMOVE', 'CART_ADD', 'CART_REMOVE', 'PURCHASE')", name=op.f('ck_user_events_event_type_values')),
    sa.CheckConstraint('user_id IS NOT NULL OR session_id IS NOT NULL', name=op.f('ck_user_events_has_actor')),
    sa.ForeignKeyConstraint(['product_id'], ['reco.products.product_id'], name=op.f('fk_user_events_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['reco.users.user_id'], name=op.f('fk_user_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_user_events')),
    schema='reco'
    )
    op.create_index('ix_user_events_product_type_time', 'user_events', ['product_id', 'event_type', 'occurred_at'], unique=False, schema='reco')
    op.create_index('ix_user_events_session_time', 'user_events', ['session_id', 'occurred_at'], unique=False, schema='reco')
    op.create_index('ix_user_events_time', 'user_events', ['occurred_at'], unique=False, schema='reco')
    op.create_index('ix_user_events_user_time', 'user_events', ['user_id', 'occurred_at'], unique=False, schema='reco')
    op.create_table('wishlist_items',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['reco.products.product_id'], name=op.f('fk_wishlist_items_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['reco.users.user_id'], name=op.f('fk_wishlist_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id', name=op.f('pk_wishlist_items')),
    schema='reco'
    )
    op.create_index(op.f('ix_wishlist_items_product_id'), 'wishlist_items', ['product_id'], unique=False, schema='reco')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_items_product_id'), table_name='wishlist_items', schema='reco')
    op.drop_table('wishlist_items', schema='reco')
    op.drop_index('ix_user_events_user_time', table_name='user_events', schema='reco')
    op.drop_index('ix_user_events_time', table_name='user_events', schema='reco')
    op.drop_index('ix_user_events_session_time', table_name='user_events', schema='reco')
    op.drop_index('ix_user_events_product_type_time', table_name='user_events', schema='reco')
    op.drop_table('user_events', schema='reco')
    op.drop_table('product_stats', schema='reco')
    op.drop_index(op.f('ix_product_skin_types_skin_type_id'), table_name='product_skin_types', schema='reco')
    op.drop_table('product_skin_types', schema='reco')
    op.drop_index(op.f('ix_product_ingredients_ingredient_id'), table_name='product_ingredients', schema='reco')
    op.drop_table('product_ingredients', schema='reco')
    op.drop_index(op.f('ix_product_concerns_concern_id'), table_name='product_concerns', schema='reco')
    op.drop_table('product_concerns', schema='reco')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items', schema='reco')
    op.drop_table('order_items', schema='reco')
    op.drop_table('user_ingredient_preferences', schema='reco')
    op.drop_table('user_concerns', schema='reco')
    op.drop_table('user_category_preferences', schema='reco')
    op.drop_table('user_brand_preferences', schema='reco')
    op.drop_index(op.f('ix_products_category_id'), table_name='products', schema='reco')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products', schema='reco')
    op.drop_index('ix_products_available_role', table_name='products', schema='reco')
    op.drop_table('products', schema='reco')
    op.drop_index('ix_orders_user_created', table_name='orders', schema='reco')
    op.drop_table('orders', schema='reco')
    op.drop_table('beauty_profiles', schema='reco')
    op.drop_table('users', schema='reco')
    op.drop_table('skin_types', schema='reco')
    op.drop_index(op.f('ix_ingredients_family'), table_name='ingredients', schema='reco')
    op.drop_table('ingredients', schema='reco')
    op.drop_table('concerns', schema='reco')
    op.drop_index(op.f('ix_categories_parent_category_id'), table_name='categories', schema='reco')
    op.drop_table('categories', schema='reco')
    op.drop_table('brands', schema='reco')
    # ### end Alembic commands ###
